// <auto-generated />
using System;
using AiSkor.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiSkor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250108055426_migration-1")]
    partial class migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AiSkor.Models.Adana_Demirspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Adana_Demirspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Alanyaspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Alanyaspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Antalyaspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Antalyaspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Basaksehispor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Basaksehirspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Besiktas", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Besiktas", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.BodrumFK", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("BodrumFK", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Caykur_Rizespor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Caykur_Rizespor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Eyupspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Eyupspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Fenerbahce", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Fenerbahce", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Fikstur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Deplasman")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("deplasman");

                    b.Property<int?>("DeplasmanSkor")
                        .HasColumnType("int")
                        .HasColumnName("deplasman_skor");

                    b.Property<string>("EvSahibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ev_sahibi");

                    b.Property<int?>("EvSkor")
                        .HasColumnType("int")
                        .HasColumnName("ev_skor");

                    b.Property<int>("Hafta")
                        .HasColumnType("int")
                        .HasColumnName("hafta");

                    b.HasKey("Id");

                    b.ToTable("Maclar", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Galatasaray", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Galatasaray", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.GaziantepFK", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("GaziantepFK", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Goztepe", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Goztepe", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Hatayspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Hatayspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Kasimpasa", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Kasimpasa", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Kayserispor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Kayserispor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Konyaspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Konyaspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.PuanDurumu", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("A")
                        .HasColumnType("int");

                    b.Property<int>("AV")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<int>("B")
                        .HasColumnType("int");

                    b.Property<int>("G")
                        .HasColumnType("int");

                    b.Property<int>("Hafta")
                        .HasColumnType("int");

                    b.Property<int>("M")
                        .HasColumnType("int");

                    b.Property<int>("O")
                        .HasColumnType("int");

                    b.Property<int>("P")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("int");

                    b.Property<string>("TakimAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("PuanDurumu", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Samsunspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Samsunspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Sivasspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Sivasspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.Trabzonspor", b =>
                {
                    b.Property<int>("No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("No"));

                    b.Property<string>("Futbolcu")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("futbolcu");

                    b.Property<string>("Mevki")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mevki");

                    b.Property<string>("Uyruk")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("uyruk");

                    b.HasKey("No");

                    b.ToTable("Trabzonspor", "dbo");
                });

            modelBuilder.Entity("AiSkor.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MacSonucu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IlkYariSkoru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ilk_yari_skoru");

                    b.Property<string>("Lig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Saat")
                        .HasColumnType("time")
                        .HasColumnName("saat");

                    b.Property<int>("Skor1")
                        .HasColumnType("int");

                    b.Property<int>("Skor2")
                        .HasColumnType("int");

                    b.Property<string>("Takim1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Takim2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("mac_sonuclari");
                });
#pragma warning restore 612, 618
        }
    }
}
